USE [master]
GO

/****** Object:  Database [StockManagment]    Script Date: 27.09.2024 11:15:17 ******/
CREATE DATABASE [StockManagment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockManagment', FILENAME = N'C:\Users\tuba.zorlu\StockManagment.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockManagment_log', FILENAME = N'C:\Users\tuba.zorlu\StockManagment_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockManagment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockManagment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockManagment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockManagment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockManagment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockManagment] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockManagment] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [StockManagment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockManagment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockManagment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockManagment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockManagment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockManagment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockManagment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockManagment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockManagment] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StockManagment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockManagment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockManagment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockManagment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockManagment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockManagment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockManagment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockManagment] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StockManagment] SET  MULTI_USER 
GO

ALTER DATABASE [StockManagment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockManagment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StockManagment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StockManagment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StockManagment] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StockManagment] SET QUERY_STORE = OFF
GO

USE [StockManagment]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [StockManagment] SET  READ_WRITE 
GO

